# Generated by Django 3.0.6 on 2020-05-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='masterrota',
            field=models.URLField(),
        ),
    ]
