# Generated by Django 3.0.6 on 2020-05-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0002_auto_20200510_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rota',
            old_name='masterrota',
            new_name='rota',
        ),
    ]
