# Generated by Django 3.0.6 on 2020-05-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0003_auto_20200510_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='tier',
            field=models.IntegerField(default=0),
        ),
    ]
